### C++ version

#include<assert.h>
#include<bits/stdc++.h>
#include<vector>
#include<sstream>
#include<regex>
#include<map>
#include<set>
float truncate_number(float number) {
    return number - floor(number);
}

### Python version

def truncate_number(number: float) -> float:
    return truncate_number(number)

### C++ version

#include<iostream>
#include<iomanip>
#include<fstream>
#include<string>
#include<vector>
#include<map>
#include<set>
#include<algorithm>
#include<utility>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
