### C++ version

#include<assert.h>
#include<bits/stdc++.h>
#include<vector>
#include<sstream>
#include<regex>
#include<map>
#include<set>
long add(long x, long y) {
    return x + y;
}

### Python version

def add(x: int, y: int) -> int:
    return x + y

### C++ version

#include<iostream>
#include<vector>
#include<map>
#include<set>
#include<string>
#include<algorithm>
#include<utility>
#include<cstdio>
#include<cstdlib>
#include<cctype>
#include<cmath>
#include<cstring>
#include<ctime>
#include<cassert>
#include<climits>
#include<iomanip>
#include<fstream>
#include<numeric>
#include<set>
#include<map>
#include<unordered_map>
#include<unordered_set>
#include<utility>
#include<sstream>
#include<iostream>
#include<iomanip>
#include<numeric>
#include<set>
#include<map>
#include<unordered_map>
#include<unordered_set>
#include<unordered_map>
#include<unordered_set>
#include<bitset>
#include<bits>
#include<algorithm>
#include<utility>
#include<string>
#include<set>
#include<map>
#include<unordered_map>
#include<unordered_set>
#include<bitset>
#include<bits>
#include<string>
#include<bitset>
#include<vector>
#include<set>
#include<map>
#include<unordered_map>
#include<unordered_set>
#include<bitset>
#include<bits>
#include<vector>
#include<bitset>
#include<bits>
#include<bitset>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bitset>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits>
#include<bits