### C++ version

#include<assert.h>
#include<bits/stdc++.h>
#include<vector>
#include<sstream>
#include<regex>
#include<map>
#include<set>
bool is_equal_to_sum_even(long n) {
    return n%2 == 0 && n >= 8;
}

### Python version

def is_equal_to_sum_even(n: int) -> bool:
    return is_equal_to_sum_even(n)

### C++ version

#include<iostream>
#include<vector>
#include<set>
#include<map>
#include<string>
#include<sstream>
#include<iomanip>
#include<fstream>
#include<iostream>
#include<algorithm>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<iterator>
#include<