from typing import Tuple

def reverse_delete(s: str, c: str) -> Tuple[str, bool]:
    """
    >>> reverse_delete("abc", "b")
    ('b', True)
    >>> reverse_delete("abc", "a")
    ('a', True)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "c")
    ('c', False)
    >>> reverse_delete("abc", "")
    ('', False)
    >>> reverse_delete("abc", "b")
    ('b', False)
    >>> reverse_delete("abc", "a")
    ('a', False)
    >>> reverse_delete("abc", "
def check(candidate):
    assert candidate('abcde', 'ae') == ('bcd', False)
    assert candidate('abcdef', 'b') == ('acdef', False)
    assert candidate('abcdedcba', 'ab') == ('cdedc', True)
    assert candidate('dwik', 'w') == ('dik', False)
    assert candidate('a', 'a') == ('', True)
    assert candidate('abcdedcba', '') == ('abcdedcba', True)
    assert candidate('abcdedcba', 'v') == ('abcdedcba', True)
    assert candidate('vabba', 'v') == ('abba', True)
    assert candidate('mamma', 'mia') == ('', True)

def test_check():
    check(reverse_delete)

test_check()
